deploy:
  runs-on: ubuntu-latest
  needs: build
  permissions:
    id-token: write
    contents: read

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
        path: ./app   # ⬅️ extract into ./app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3FAB52A70D94D14B7308B1059FA4DC1 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9381D7F27FF348A0B877273D891EAFC5 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1C284838966F41DEAC33696F91EB1C68 }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'uccd2223-assignment'
        slot-name: 'Production'
        package: ./app   # ⬅️ deploy the extracted artifact
