jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Archive Web Content
        uses: actions/upload-artifact@v4
        with:
          name: web-app-content
          path: . # <-- Upload the ENTIRE repository content, as index.html and assets are at root

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Web Content artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app-content
          path: ./site_root # <-- Download into a temporary folder named 'site_root'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3FAB52A70D94D14B7308B1059FA4DC1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9381D7F27FF348A0B877273D891EAFC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1C284838966F41DEAC33696F91EB1C68 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uccd2223-assignment'
          slot-name: 'Production'
          package: ./site_root # <-- Deploy the contents of the 'site_root' folder